#!/bin/bash

function init_rvm {
  if [[ -s "$HOME/.rvm/scripts/rvm" ]] ; then
    source "$HOME/.rvm/scripts/rvm"
  elif [[ -s "/usr/local/rvm/scripts/rvm" ]] ; then
    source "/usr/local/rvm/scripts/rvm"
  else
    printf "ERROR: An RVM installation was not found.\n"
  fi

  rvm use $CI_RUBY --create
}

function ci_env_run {
  RAILS_ENV=test $1
}

function exit_on_error {
  if [ ! $? -eq 0 ]; then
    echo "~> running '$1' failed" 1>&2
    exit 1
  fi
}

function ci_env_run_err {
  ci_env_run "$1"
  exit_on_error "$1"
}

function run_cucumber_profile_with_rerun {
  rm -f tmp/rerun.txt
  ci_env_run "bundler_stubs/cucumber features -p $1 --format rerun --out tmp/rerun.txt --format html --out=tmp/reports/cucumber_$1.html"
  if [ ! $? -eq 0 ]; then
    printf "~> Some features failed. Trying them again:\n"
    cat tmp/rerun.txt
    printf "\n"

    ci_env_run_err "bundler_stubs/cucumber @tmp/rerun.txt -p $1 --format html --out=tmp/reports/cucumber_$1_rerun.html"
  fi
}
